### ISSUE TITLE
Add support for DirectXTex

### ISSUE THREAD

**Issue by Sharlikran** [0xC0000054/pdn-ddsfiletype-plus#1]
Would you be willing to add support for files made with [DirectXTex](https://github.com/Microsoft/DirectXTex/releases)?

**Comment by 0xC0000054** [comment]
This plugin already uses the July 2017 release of DirectXTex to load and save files.

Do you have any examples of files created by DirectXTex that fail to load using this plugin?

**Comment by Sharlikran** [comment]
I will get you some test files as soon as I can, just some RL things came up.

**Comment by 0xC0000054** [comment]
I ran a quick test using the [OpenIL DDS samples](https://sourceforge.net/p/openil/svn/HEAD/tree/trunk/Test%20Images/DDS/) and the only formats DirectXTex failed to load were a few DirectX 9 stencil buffer and bump map formats.

If you are trying to load a cube map or texture array this plugin will only load the first image in the file.

**Comment by Sharlikran** [comment]
I am closing this because it has become stale and I never provided any sample files. If I convert some textures and it happens again I will reopen it and try to provide them this time. Sorry about this.
