### ISSUE TITLE
When overwriting "save configuration" does not read from the file it's overwriting.

### ISSUE THREAD

**Issue by DeathWrench** [0xC0000054/pdn-ddsfiletype-plus#13]
I can't get texture to load in game, I don't know what file type to save as to get it to read. Only option is to save as every single one and try all combinations of error metric, mip maps, and what not.
![alt text](https://cdn.discordapp.com/attachments/515842332201975821/845372456445411390/unknown.png)
I feel like for overwriting it should default "save configuration" settings to the files originals

**Comment by 0xC0000054** [comment]
>  I feel like for overwriting it should default "save configuration" settings to the files originals

I agree, but Paint.NET does not currently have the infrastructure that would allow the plugin to support this feature.
As a workaround you can use the DirectXTex [Texdiag](https://github.com/microsoft/DirectXTex/wiki/Texdiag) utility to get the configuration of the original file.

**Comment by DeathWrench** [comment]
That helped a lot. Thanks for the pointer! I found out that it had nothing to do with the texture itself and everything to do with Archive2 for packing .ba2's for use with Bethesda games. 
I had to set these settings to get the textures to load. (just in case someone else needs it)
![alt text](https://cdn.discordapp.com/attachments/515842332201975821/845582723842441216/unknown.png)
