### ISSUE TITLE
Low quality DXT compression?

### ISSUE THREAD

**Issue by xrModder** [0xC0000054/pdn-ddsfiletype-plus#15]
I am using Paint.NET to edit and save DDS textures. I have noticed that Paint.NET with this plugin saves textures in a worse quality than other tools. For example, on a very old X-Ray SDK (S.T.A.L.K.E.R.), texture quality is better.
<details>
  <summary>Paint.NET DXT1</summary>

![PaintNET_DXT1](https://user-images.githubusercontent.com/53347567/222729973-da8ce9bf-df18-4a72-9c53-1a68fc08ce4f.png)
</details>
<details>
  <summary>X-Ray SDK DXT1</summary>

![XRaySDK_DXT1](https://user-images.githubusercontent.com/53347567/222730474-7b4420c7-3be2-4fbd-9846-3531d9a16e42.png)
</details>

Sorry for my English (I write through a translator).

**Comment by 0xC0000054** [comment]
It appears that this issue is caused by the default color matching algorithm DirectXTex uses for DXT1.
DirectXTex has an option to use Floyd–Steinberg dithering when compressing DXT1-DXT5, but DDSFileTypePlus version 1.11.1 does not use it.

<details>
<summary>Paint.NET DXT1 with Floyd–Steinberg dithering</summary>

![dxt1 with dithering](https://user-images.githubusercontent.com/26996983/222766508-76b1e672-b19c-4679-9c88-b769e7e59abc.png)

</details>

The Floyd–Steinberg dithering reduces the number of visible compression artifacts, but the image still has more compression artifacts than your X-Ray SDK image.
The blue area at the top of the image has visible rings/banding in all 3 images.

Do you have an uncompressed source image for comparison?

**Comment by xrModder** [comment]
> Do you have an uncompressed source image for comparison?

<details>
  <summary>clear_sky_horizontal_cross.png</summary>

![clear_sky_horizontal_cross](https://user-images.githubusercontent.com/53347567/222780685-14a56ff1-cf8c-4493-be16-8e073ebf5922.png)
</details>

**Comment by rickbrew** [comment]
Are these 8-bit per pixel formats? (e.g. indexed)

**Comment by 0xC0000054** [comment]
> Are these 8-bit per pixel formats? (e.g. indexed)

The PNG images are 32-bit. 
DXT1, DXT3 and DXT5 (BC1, BC2 and BC3) use the same [4x4 pixel block compression with RGB 565](https://learn.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-block-compression#bc1) format for the color data,

For testing I added a checkbox for the Floyd–Steinberg dithering to the Save UI. The checkbox currently defaults to true, which should be fine for most images.

<details>
<summary>DDS save UI with dithering</summary>

![DDS save UI with dithering](https://user-images.githubusercontent.com/26996983/222864069-78a2404a-bcf2-44cb-84cb-a69cb19d5ea4.png)

</details>

**Comment by 0xC0000054** [comment]
Version 1.11.2 includes the dithering check box I mentioned above. https://github.com/0xC0000054/pdn-ddsfiletype-plus/releases

**Comment by xrModder** [comment]
> Version 1.11.2 includes the dithering check box I mentioned above. https://github.com/0xC0000054/pdn-ddsfiletype-plus/releases

The quality has improved but is still a bit worse compared to the X-Ray SDK.

**Comment by 0xC0000054** [comment]
What game are you trying to mod?

You may want to try saving the skybox image as uncompressed `B8G8R8A8 (Linear, A8R8G8B8)` and see if the game can load it.

I ran a few more tests with other DXT compression tools:
The NVIDIA Texture Tools version 2023.1 DXT1 compressor had a similar number of artifacts to the DirectXTex image with dithering.
The squish DXT compression library that was used by Paint.NET 4.2.1 and earlier was worse than DirectXTex with dithering.

I am not sure why the X-Ray SDK produces higher quality output, perhaps it has a special routine for handling DXT1 images with gradients.

I am considering filing an issue in the DirectXTex repository about this. The developers there may be able to provide more information about why that skybox image has so many artifacts when saved as DXT1.

**Comment by xrModder** [comment]
It's not about the skybox or game, but about the quality of saving DDS textures with DXT compression. I did a test of saving a regular texture (part of a skybox) and a skybox<sup>*</sup> texture in the X-Ray SDK with and without the "dither" flag. For some reason, the result is the better quality than Paint.NET with the latest plugin. Textures in the archive: [Textures.zip](https://github.com/0xC0000054/pdn-ddsfiletype-plus/files/10892086/Textures.zip)

<details>
  <summary>X-Ray SDK (no dither)</summary>

https://user-images.githubusercontent.com/53347567/222968504-39f358a5-571b-47af-881c-04d8cb0daeff.mp4
</details>

<details>
  <summary>X-Ray SDK (dither)</summary>

https://user-images.githubusercontent.com/53347567/222968496-2923de3e-36eb-4f9a-980f-53bb044912fe.mp4
</details>

<sup>*</sup> X-Ray SDK accepts only linear (strip xyz) skybox texture, but this does not affect the quality of the final texture.

**Comment by 0xC0000054** [comment]
There is nothing else I can do in the plugin to improve the DXT compression quality. The Floyd–Steinberg dithering is the only option that DirectXTex provides.

**Comment by xrModder** [comment]
Adding a dither flag does not solve the problem. Even without the dither flag, the X-Ray SDK compresses textures of better quality than DirectXTex. I'm not sure, but it seems that DirectXTex loses a significant amount of detail when compressing BC and this requires reworking the compression algorithm.
