### ISSUE TITLE
Distortion after saving image having transparent pixels in BC1 format

### ISSUE THREAD

**Issue by MightyEagle82** [0xC0000054/pdn-ddsfiletype-plus#17]
I tried to save PNG image having transparent pixels into different BC formats and found that the image in BC1 format becomes sharper (see test_bc1a.dds).

![the original image](https://github.com/0xC0000054/pdn-ddsfiletype-plus/assets/3224608/b6e9d2d5-a2d7-4c5a-87c0-9a9e085fa5d2)

Compare the following DDS files between themselves and the original image.

[dds.zip](https://github.com/0xC0000054/pdn-ddsfiletype-plus/files/13908018/dds.zip)

BC2, BC3 and BC7 formats support alpha channel so the original image is converted fine.
But even images in BC4 and BC5 formats that don't support transparency are still similar to the original one.
Also after adding to the original image opaque layer in Paint.NET I saved it in BC1 format to show how I expected it supposed to look like.

**Comment by 0xC0000054** [comment]
I think that could just be how the BC1 alpha format works. It only supports alpha values of 0 and 255, so it has to convert the semi-transparent pixels to either fully transparent or fully opaque.
For the BC1 image with an opaque background, Paint.NET handles the alpha blending and the BC1 encoder receives an image that does not have any transparency.

**Comment by MightyEagle82** [comment]
BC4 and BC5 formats don't support transparency at all. But converted images are still similar to the original one.

P. S. Please read my message carefully.

**Comment by 0xC0000054** [comment]
BC4 and BC5 are not the same compression format as BC1.  I do not have any idea what is going on with your `test_bc1a.dds` image.

This plugin uses the BC1 encoder from DirectXTex, you should refile your issue in that repository. https://github.com/microsoft/DirectXTex/issues
The DirectXTex developers may have a better idea of what is causing the problem.

**Comment by MightyEagle82** [comment]
Thank you for the pointing. I understand that isn't the plugin related issue.
