### ISSUE TITLE
Add link to plugin page in the SaveConfigWidget

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-ddsfiletype-plus#7]
I think it'd be useful for people to know where the DDS plugin comes from and who the author is, and that they can install a newer version if they need to (probably need to add instructions to the plugin's forum post?).

You can add a clickable link by using a `UriProperty` in the `PropertyCollection`.

**Comment by rickbrew** [comment]
Also I noticed that the plugin's forum page has the date in it: https://forums.getpaint.net/topic/111731-dds-filetype-plus-2019-05-29/

I think that means there isn't a stable URL because it will change when the title is changed with the next update.

🤔

**Comment by 0xC0000054** [comment]
>Also I noticed that the plugin's forum page has the date in it: https://forums.getpaint.net/topic/111731-dds-filetype-plus-2019-05-29/ ...

@rickbrew 

I think that the forum software only looks at the topic number that precedes the thread name.

The Plugin Index entry uses the following link:
https://forums.getpaint.net/topic/111731-i

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0xC0000054** [comment]
@rickbrew 

Any suggestions on the what to use for the link Description?
I was thinking `Forum thread` or `Plugin thread`, but there are probably better options.

**Comment by rickbrew** [comment]
Brainstorming here ...

`More info ...` seems too nebulous

For these, I think it may be confusing, "Wait I didn't install a plugin?" :
`DDS plugin info ...`
`About DDS plugin ...`

Maybe a header? Could even have two links?
```
More Info
-----------
Forum Discussion
GitHub
```
